// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sockaddr_tipc {
 *     unsigned short family;
 *     unsigned char addrtype;
 *     signed char scope;
 *     union {
 *         struct tipc_socket_addr id;
 *         struct tipc_service_range nameseq;
 *         struct {
 *             struct tipc_service_addr name;
 *             __u32 domain;
 *         } name;
 *     } addr;
 * }
 * }
 */
public class sockaddr_tipc {

    sockaddr_tipc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tipc_h.C_SHORT.withName("family"),
        tipc_h.C_CHAR.withName("addrtype"),
        tipc_h.C_CHAR.withName("scope"),
        sockaddr_tipc.addr.layout().withName("addr")
    ).withName("sockaddr_tipc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort family$LAYOUT = (OfShort)$LAYOUT.select(groupElement("family"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned short family
     * }
     */
    public static final OfShort family$layout() {
        return family$LAYOUT;
    }

    private static final long family$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned short family
     * }
     */
    public static final long family$offset() {
        return family$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short family
     * }
     */
    public static short family(MemorySegment struct) {
        return struct.get(family$LAYOUT, family$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short family
     * }
     */
    public static void family(MemorySegment struct, short fieldValue) {
        struct.set(family$LAYOUT, family$OFFSET, fieldValue);
    }

    private static final OfByte addrtype$LAYOUT = (OfByte)$LAYOUT.select(groupElement("addrtype"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char addrtype
     * }
     */
    public static final OfByte addrtype$layout() {
        return addrtype$LAYOUT;
    }

    private static final long addrtype$OFFSET = 2;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char addrtype
     * }
     */
    public static final long addrtype$offset() {
        return addrtype$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char addrtype
     * }
     */
    public static byte addrtype(MemorySegment struct) {
        return struct.get(addrtype$LAYOUT, addrtype$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char addrtype
     * }
     */
    public static void addrtype(MemorySegment struct, byte fieldValue) {
        struct.set(addrtype$LAYOUT, addrtype$OFFSET, fieldValue);
    }

    private static final OfByte scope$LAYOUT = (OfByte)$LAYOUT.select(groupElement("scope"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * signed char scope
     * }
     */
    public static final OfByte scope$layout() {
        return scope$LAYOUT;
    }

    private static final long scope$OFFSET = 3;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * signed char scope
     * }
     */
    public static final long scope$offset() {
        return scope$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * signed char scope
     * }
     */
    public static byte scope(MemorySegment struct) {
        return struct.get(scope$LAYOUT, scope$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * signed char scope
     * }
     */
    public static void scope(MemorySegment struct, byte fieldValue) {
        struct.set(scope$LAYOUT, scope$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     struct tipc_socket_addr id;
     *     struct tipc_service_range nameseq;
     *     struct {
     *         struct tipc_service_addr name;
     *         __u32 domain;
     *     } name;
     * }
     * }
     */
    public static class addr {

        addr() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            tipc_socket_addr.layout().withName("id"),
            tipc_service_range.layout().withName("nameseq"),
            sockaddr_tipc.addr.name.layout().withName("name")
        ).withName("$anon$161:2");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final GroupLayout id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("id"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct tipc_socket_addr id
         * }
         */
        public static final GroupLayout id$layout() {
            return id$LAYOUT;
        }

        private static final long id$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct tipc_socket_addr id
         * }
         */
        public static final long id$offset() {
            return id$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct tipc_socket_addr id
         * }
         */
        public static MemorySegment id(MemorySegment union) {
            return union.asSlice(id$OFFSET, id$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct tipc_socket_addr id
         * }
         */
        public static void id(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, id$OFFSET, id$LAYOUT.byteSize());
        }

        private static final GroupLayout nameseq$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("nameseq"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct tipc_service_range nameseq
         * }
         */
        public static final GroupLayout nameseq$layout() {
            return nameseq$LAYOUT;
        }

        private static final long nameseq$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct tipc_service_range nameseq
         * }
         */
        public static final long nameseq$offset() {
            return nameseq$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct tipc_service_range nameseq
         * }
         */
        public static MemorySegment nameseq(MemorySegment union) {
            return union.asSlice(nameseq$OFFSET, nameseq$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct tipc_service_range nameseq
         * }
         */
        public static void nameseq(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, nameseq$OFFSET, nameseq$LAYOUT.byteSize());
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     struct tipc_service_addr name;
         *     __u32 domain;
         * }
         * }
         */
        public static class name {

            name() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                tipc_service_addr.layout().withName("name"),
                tipc_h.C_INT.withName("domain")
            ).withName("$anon$164:3");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final GroupLayout name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("name"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * struct tipc_service_addr name
             * }
             */
            public static final GroupLayout name$layout() {
                return name$LAYOUT;
            }

            private static final long name$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * struct tipc_service_addr name
             * }
             */
            public static final long name$offset() {
                return name$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * struct tipc_service_addr name
             * }
             */
            public static MemorySegment name(MemorySegment struct) {
                return struct.asSlice(name$OFFSET, name$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * struct tipc_service_addr name
             * }
             */
            public static void name(MemorySegment struct, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, struct, name$OFFSET, name$LAYOUT.byteSize());
            }

            private static final OfInt domain$LAYOUT = (OfInt)$LAYOUT.select(groupElement("domain"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * __u32 domain
             * }
             */
            public static final OfInt domain$layout() {
                return domain$LAYOUT;
            }

            private static final long domain$OFFSET = 8;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * __u32 domain
             * }
             */
            public static final long domain$offset() {
                return domain$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * __u32 domain
             * }
             */
            public static int domain(MemorySegment struct) {
                return struct.get(domain$LAYOUT, domain$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * __u32 domain
             * }
             */
            public static void domain(MemorySegment struct, int fieldValue) {
                struct.set(domain$LAYOUT, domain$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("name"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     struct tipc_service_addr name;
         *     __u32 domain;
         * } name
         * }
         */
        public static final GroupLayout name$layout() {
            return name$LAYOUT;
        }

        private static final long name$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     struct tipc_service_addr name;
         *     __u32 domain;
         * } name
         * }
         */
        public static final long name$offset() {
            return name$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     struct tipc_service_addr name;
         *     __u32 domain;
         * } name
         * }
         */
        public static MemorySegment name(MemorySegment union) {
            return union.asSlice(name$OFFSET, name$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     struct tipc_service_addr name;
         *     __u32 domain;
         * } name
         * }
         */
        public static void name(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, name$OFFSET, name$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout addr$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     struct tipc_socket_addr id;
     *     struct tipc_service_range nameseq;
     *     struct {
     *         struct tipc_service_addr name;
     *         __u32 domain;
     *     } name;
     * } addr
     * }
     */
    public static final GroupLayout addr$layout() {
        return addr$LAYOUT;
    }

    private static final long addr$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     struct tipc_socket_addr id;
     *     struct tipc_service_range nameseq;
     *     struct {
     *         struct tipc_service_addr name;
     *         __u32 domain;
     *     } name;
     * } addr
     * }
     */
    public static final long addr$offset() {
        return addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     struct tipc_socket_addr id;
     *     struct tipc_service_range nameseq;
     *     struct {
     *         struct tipc_service_addr name;
     *         __u32 domain;
     *     } name;
     * } addr
     * }
     */
    public static MemorySegment addr(MemorySegment struct) {
        return struct.asSlice(addr$OFFSET, addr$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     struct tipc_socket_addr id;
     *     struct tipc_service_range nameseq;
     *     struct {
     *         struct tipc_service_addr name;
     *         __u32 domain;
     *     } name;
     * } addr
     * }
     */
    public static void addr(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, addr$OFFSET, addr$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

