// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tipc_event {
 *     __u32 event;
 *     __u32 found_lower;
 *     __u32 found_upper;
 *     struct tipc_socket_addr port;
 *     struct tipc_subscr s;
 * }
 * }
 */
public class tipc_event {

    tipc_event() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tipc_h.C_INT.withName("event"),
        tipc_h.C_INT.withName("found_lower"),
        tipc_h.C_INT.withName("found_upper"),
        tipc_socket_addr.layout().withName("port"),
        tipc_subscr.layout().withName("s")
    ).withName("tipc_event");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt event$LAYOUT = (OfInt)$LAYOUT.select(groupElement("event"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 event
     * }
     */
    public static final OfInt event$layout() {
        return event$LAYOUT;
    }

    private static final long event$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 event
     * }
     */
    public static final long event$offset() {
        return event$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 event
     * }
     */
    public static int event(MemorySegment struct) {
        return struct.get(event$LAYOUT, event$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 event
     * }
     */
    public static void event(MemorySegment struct, int fieldValue) {
        struct.set(event$LAYOUT, event$OFFSET, fieldValue);
    }

    private static final OfInt found_lower$LAYOUT = (OfInt)$LAYOUT.select(groupElement("found_lower"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 found_lower
     * }
     */
    public static final OfInt found_lower$layout() {
        return found_lower$LAYOUT;
    }

    private static final long found_lower$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 found_lower
     * }
     */
    public static final long found_lower$offset() {
        return found_lower$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 found_lower
     * }
     */
    public static int found_lower(MemorySegment struct) {
        return struct.get(found_lower$LAYOUT, found_lower$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 found_lower
     * }
     */
    public static void found_lower(MemorySegment struct, int fieldValue) {
        struct.set(found_lower$LAYOUT, found_lower$OFFSET, fieldValue);
    }

    private static final OfInt found_upper$LAYOUT = (OfInt)$LAYOUT.select(groupElement("found_upper"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 found_upper
     * }
     */
    public static final OfInt found_upper$layout() {
        return found_upper$LAYOUT;
    }

    private static final long found_upper$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 found_upper
     * }
     */
    public static final long found_upper$offset() {
        return found_upper$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 found_upper
     * }
     */
    public static int found_upper(MemorySegment struct) {
        return struct.get(found_upper$LAYOUT, found_upper$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 found_upper
     * }
     */
    public static void found_upper(MemorySegment struct, int fieldValue) {
        struct.set(found_upper$LAYOUT, found_upper$OFFSET, fieldValue);
    }

    private static final GroupLayout port$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("port"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct tipc_socket_addr port
     * }
     */
    public static final GroupLayout port$layout() {
        return port$LAYOUT;
    }

    private static final long port$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct tipc_socket_addr port
     * }
     */
    public static final long port$offset() {
        return port$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct tipc_socket_addr port
     * }
     */
    public static MemorySegment port(MemorySegment struct) {
        return struct.asSlice(port$OFFSET, port$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct tipc_socket_addr port
     * }
     */
    public static void port(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, port$OFFSET, port$LAYOUT.byteSize());
    }

    private static final GroupLayout s$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("s"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct tipc_subscr s
     * }
     */
    public static final GroupLayout s$layout() {
        return s$LAYOUT;
    }

    private static final long s$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct tipc_subscr s
     * }
     */
    public static final long s$offset() {
        return s$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct tipc_subscr s
     * }
     */
    public static MemorySegment s(MemorySegment struct) {
        return struct.asSlice(s$OFFSET, s$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct tipc_subscr s
     * }
     */
    public static void s(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, s$OFFSET, s$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

