// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tipc_socket_addr {
 *     __u32 ref;
 *     __u32 node;
 * }
 * }
 */
public class tipc_socket_addr {

    tipc_socket_addr() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tipc_h.C_INT.withName("ref"),
        tipc_h.C_INT.withName("node")
    ).withName("tipc_socket_addr");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt ref$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 ref
     * }
     */
    public static final OfInt ref$layout() {
        return ref$LAYOUT;
    }

    private static final long ref$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 ref
     * }
     */
    public static final long ref$offset() {
        return ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 ref
     * }
     */
    public static int ref(MemorySegment struct) {
        return struct.get(ref$LAYOUT, ref$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 ref
     * }
     */
    public static void ref(MemorySegment struct, int fieldValue) {
        struct.set(ref$LAYOUT, ref$OFFSET, fieldValue);
    }

    private static final OfInt node$LAYOUT = (OfInt)$LAYOUT.select(groupElement("node"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 node
     * }
     */
    public static final OfInt node$layout() {
        return node$LAYOUT;
    }

    private static final long node$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 node
     * }
     */
    public static final long node$offset() {
        return node$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 node
     * }
     */
    public static int node(MemorySegment struct) {
        return struct.get(node$LAYOUT, node$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 node
     * }
     */
    public static void node(MemorySegment struct, int fieldValue) {
        struct.set(node$LAYOUT, node$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

