// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tipc_aead_key {
 *     char alg_name[32];
 *     unsigned int keylen;
 *     char key[];
 * }
 * }
 */
public class tipc_aead_key {

    tipc_aead_key() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(32, tipc_h.C_CHAR).withName("alg_name"),
        tipc_h.C_INT.withName("keylen"),
        MemoryLayout.sequenceLayout(0, tipc_h.C_CHAR).withName("key")
    ).withName("tipc_aead_key");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout alg_name$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("alg_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char alg_name[32]
     * }
     */
    public static final SequenceLayout alg_name$layout() {
        return alg_name$LAYOUT;
    }

    private static final long alg_name$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char alg_name[32]
     * }
     */
    public static final long alg_name$offset() {
        return alg_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char alg_name[32]
     * }
     */
    public static MemorySegment alg_name(MemorySegment struct) {
        return struct.asSlice(alg_name$OFFSET, alg_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char alg_name[32]
     * }
     */
    public static void alg_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, alg_name$OFFSET, alg_name$LAYOUT.byteSize());
    }

    private static long[] alg_name$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char alg_name[32]
     * }
     */
    public static long[] alg_name$dimensions() {
        return alg_name$DIMS;
    }
    private static final VarHandle alg_name$ELEM_HANDLE = alg_name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char alg_name[32]
     * }
     */
    public static byte alg_name(MemorySegment struct, long index0) {
        return (byte)alg_name$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char alg_name[32]
     * }
     */
    public static void alg_name(MemorySegment struct, long index0, byte fieldValue) {
        alg_name$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfInt keylen$LAYOUT = (OfInt)$LAYOUT.select(groupElement("keylen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int keylen
     * }
     */
    public static final OfInt keylen$layout() {
        return keylen$LAYOUT;
    }

    private static final long keylen$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int keylen
     * }
     */
    public static final long keylen$offset() {
        return keylen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int keylen
     * }
     */
    public static int keylen(MemorySegment struct) {
        return struct.get(keylen$LAYOUT, keylen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int keylen
     * }
     */
    public static void keylen(MemorySegment struct, int fieldValue) {
        struct.set(keylen$LAYOUT, keylen$OFFSET, fieldValue);
    }

    private static final SequenceLayout key$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char key[]
     * }
     */
    public static final SequenceLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = 36;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char key[]
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char key[]
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.asSlice(key$OFFSET, key$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char key[]
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, key$OFFSET, key$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

