// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tipc_sioc_nodeid_req {
 *     __u32 peer;
 *     char node_id[16];
 * }
 * }
 */
public class tipc_sioc_nodeid_req {

    tipc_sioc_nodeid_req() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tipc_h.C_INT.withName("peer"),
        MemoryLayout.sequenceLayout(16, tipc_h.C_CHAR).withName("node_id")
    ).withName("tipc_sioc_nodeid_req");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt peer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("peer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static final OfInt peer$layout() {
        return peer$LAYOUT;
    }

    private static final long peer$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static final long peer$offset() {
        return peer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static int peer(MemorySegment struct) {
        return struct.get(peer$LAYOUT, peer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static void peer(MemorySegment struct, int fieldValue) {
        struct.set(peer$LAYOUT, peer$OFFSET, fieldValue);
    }

    private static final SequenceLayout node_id$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("node_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char node_id[16]
     * }
     */
    public static final SequenceLayout node_id$layout() {
        return node_id$LAYOUT;
    }

    private static final long node_id$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char node_id[16]
     * }
     */
    public static final long node_id$offset() {
        return node_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char node_id[16]
     * }
     */
    public static MemorySegment node_id(MemorySegment struct) {
        return struct.asSlice(node_id$OFFSET, node_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char node_id[16]
     * }
     */
    public static void node_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, node_id$OFFSET, node_id$LAYOUT.byteSize());
    }

    private static long[] node_id$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char node_id[16]
     * }
     */
    public static long[] node_id$dimensions() {
        return node_id$DIMS;
    }
    private static final VarHandle node_id$ELEM_HANDLE = node_id$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char node_id[16]
     * }
     */
    public static byte node_id(MemorySegment struct, long index0) {
        return (byte)node_id$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char node_id[16]
     * }
     */
    public static void node_id(MemorySegment struct, long index0, byte fieldValue) {
        node_id$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

