// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tipc_sioc_ln_req {
 *     __u32 peer;
 *     __u32 bearer_id;
 *     char linkname[68];
 * }
 * }
 */
public class tipc_sioc_ln_req {

    tipc_sioc_ln_req() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tipc_h.C_INT.withName("peer"),
        tipc_h.C_INT.withName("bearer_id"),
        MemoryLayout.sequenceLayout(68, tipc_h.C_CHAR).withName("linkname")
    ).withName("tipc_sioc_ln_req");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt peer$LAYOUT = (OfInt)$LAYOUT.select(groupElement("peer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static final OfInt peer$layout() {
        return peer$LAYOUT;
    }

    private static final long peer$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static final long peer$offset() {
        return peer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static int peer(MemorySegment struct) {
        return struct.get(peer$LAYOUT, peer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 peer
     * }
     */
    public static void peer(MemorySegment struct, int fieldValue) {
        struct.set(peer$LAYOUT, peer$OFFSET, fieldValue);
    }

    private static final OfInt bearer_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bearer_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 bearer_id
     * }
     */
    public static final OfInt bearer_id$layout() {
        return bearer_id$LAYOUT;
    }

    private static final long bearer_id$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 bearer_id
     * }
     */
    public static final long bearer_id$offset() {
        return bearer_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 bearer_id
     * }
     */
    public static int bearer_id(MemorySegment struct) {
        return struct.get(bearer_id$LAYOUT, bearer_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 bearer_id
     * }
     */
    public static void bearer_id(MemorySegment struct, int fieldValue) {
        struct.set(bearer_id$LAYOUT, bearer_id$OFFSET, fieldValue);
    }

    private static final SequenceLayout linkname$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("linkname"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char linkname[68]
     * }
     */
    public static final SequenceLayout linkname$layout() {
        return linkname$LAYOUT;
    }

    private static final long linkname$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char linkname[68]
     * }
     */
    public static final long linkname$offset() {
        return linkname$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char linkname[68]
     * }
     */
    public static MemorySegment linkname(MemorySegment struct) {
        return struct.asSlice(linkname$OFFSET, linkname$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char linkname[68]
     * }
     */
    public static void linkname(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, linkname$OFFSET, linkname$LAYOUT.byteSize());
    }

    private static long[] linkname$DIMS = { 68 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char linkname[68]
     * }
     */
    public static long[] linkname$dimensions() {
        return linkname$DIMS;
    }
    private static final VarHandle linkname$ELEM_HANDLE = linkname$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char linkname[68]
     * }
     */
    public static byte linkname(MemorySegment struct, long index0) {
        return (byte)linkname$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char linkname[68]
     * }
     */
    public static void linkname(MemorySegment struct, long index0, byte fieldValue) {
        linkname$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

