// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tipc_subscr {
 *     struct tipc_service_range seq;
 *     __u32 timeout;
 *     __u32 filter;
 *     char usr_handle[8];
 * }
 * }
 */
public class tipc_subscr {

    tipc_subscr() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tipc_service_range.layout().withName("seq"),
        tipc_h.C_INT.withName("timeout"),
        tipc_h.C_INT.withName("filter"),
        MemoryLayout.sequenceLayout(8, tipc_h.C_CHAR).withName("usr_handle")
    ).withName("tipc_subscr");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout seq$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("seq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct tipc_service_range seq
     * }
     */
    public static final GroupLayout seq$layout() {
        return seq$LAYOUT;
    }

    private static final long seq$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct tipc_service_range seq
     * }
     */
    public static final long seq$offset() {
        return seq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct tipc_service_range seq
     * }
     */
    public static MemorySegment seq(MemorySegment struct) {
        return struct.asSlice(seq$OFFSET, seq$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct tipc_service_range seq
     * }
     */
    public static void seq(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, seq$OFFSET, seq$LAYOUT.byteSize());
    }

    private static final OfInt timeout$LAYOUT = (OfInt)$LAYOUT.select(groupElement("timeout"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 timeout
     * }
     */
    public static final OfInt timeout$layout() {
        return timeout$LAYOUT;
    }

    private static final long timeout$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 timeout
     * }
     */
    public static final long timeout$offset() {
        return timeout$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 timeout
     * }
     */
    public static int timeout(MemorySegment struct) {
        return struct.get(timeout$LAYOUT, timeout$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 timeout
     * }
     */
    public static void timeout(MemorySegment struct, int fieldValue) {
        struct.set(timeout$LAYOUT, timeout$OFFSET, fieldValue);
    }

    private static final OfInt filter$LAYOUT = (OfInt)$LAYOUT.select(groupElement("filter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 filter
     * }
     */
    public static final OfInt filter$layout() {
        return filter$LAYOUT;
    }

    private static final long filter$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 filter
     * }
     */
    public static final long filter$offset() {
        return filter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 filter
     * }
     */
    public static int filter(MemorySegment struct) {
        return struct.get(filter$LAYOUT, filter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 filter
     * }
     */
    public static void filter(MemorySegment struct, int fieldValue) {
        struct.set(filter$LAYOUT, filter$OFFSET, fieldValue);
    }

    private static final SequenceLayout usr_handle$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("usr_handle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char usr_handle[8]
     * }
     */
    public static final SequenceLayout usr_handle$layout() {
        return usr_handle$LAYOUT;
    }

    private static final long usr_handle$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char usr_handle[8]
     * }
     */
    public static final long usr_handle$offset() {
        return usr_handle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char usr_handle[8]
     * }
     */
    public static MemorySegment usr_handle(MemorySegment struct) {
        return struct.asSlice(usr_handle$OFFSET, usr_handle$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char usr_handle[8]
     * }
     */
    public static void usr_handle(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, usr_handle$OFFSET, usr_handle$LAYOUT.byteSize());
    }

    private static long[] usr_handle$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char usr_handle[8]
     * }
     */
    public static long[] usr_handle$dimensions() {
        return usr_handle$DIMS;
    }
    private static final VarHandle usr_handle$ELEM_HANDLE = usr_handle$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char usr_handle[8]
     * }
     */
    public static byte usr_handle(MemorySegment struct, long index0) {
        return (byte)usr_handle$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char usr_handle[8]
     * }
     */
    public static void usr_handle(MemorySegment struct, long index0, byte fieldValue) {
        usr_handle$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

