// Generated by jextract

package zmq.io.net.tipc.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class tipc_h {

    tipc_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }


    static {
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;
    private static final int __BITS_PER_LONG = (int)64L;
    /**
     * {@snippet lang=c :
     * #define __BITS_PER_LONG 64
     * }
     */
    public static int __BITS_PER_LONG() {
        return __BITS_PER_LONG;
    }
    private static final int __FD_SETSIZE = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define __FD_SETSIZE 1024
     * }
     */
    public static int __FD_SETSIZE() {
        return __FD_SETSIZE;
    }
    private static final int FIOSETOWN = (int)35073L;
    /**
     * {@snippet lang=c :
     * #define FIOSETOWN 35073
     * }
     */
    public static int FIOSETOWN() {
        return FIOSETOWN;
    }
    private static final int SIOCSPGRP = (int)35074L;
    /**
     * {@snippet lang=c :
     * #define SIOCSPGRP 35074
     * }
     */
    public static int SIOCSPGRP() {
        return SIOCSPGRP;
    }
    private static final int FIOGETOWN = (int)35075L;
    /**
     * {@snippet lang=c :
     * #define FIOGETOWN 35075
     * }
     */
    public static int FIOGETOWN() {
        return FIOGETOWN;
    }
    private static final int SIOCGPGRP = (int)35076L;
    /**
     * {@snippet lang=c :
     * #define SIOCGPGRP 35076
     * }
     */
    public static int SIOCGPGRP() {
        return SIOCGPGRP;
    }
    private static final int SIOCATMARK = (int)35077L;
    /**
     * {@snippet lang=c :
     * #define SIOCATMARK 35077
     * }
     */
    public static int SIOCATMARK() {
        return SIOCATMARK;
    }
    private static final int SIOCGSTAMP_OLD = (int)35078L;
    /**
     * {@snippet lang=c :
     * #define SIOCGSTAMP_OLD 35078
     * }
     */
    public static int SIOCGSTAMP_OLD() {
        return SIOCGSTAMP_OLD;
    }
    private static final int SIOCGSTAMPNS_OLD = (int)35079L;
    /**
     * {@snippet lang=c :
     * #define SIOCGSTAMPNS_OLD 35079
     * }
     */
    public static int SIOCGSTAMPNS_OLD() {
        return SIOCGSTAMPNS_OLD;
    }
    private static final int SOCK_IOC_TYPE = (int)137L;
    /**
     * {@snippet lang=c :
     * #define SOCK_IOC_TYPE 137
     * }
     */
    public static int SOCK_IOC_TYPE() {
        return SOCK_IOC_TYPE;
    }
    private static final int SIOCADDRT = (int)35083L;
    /**
     * {@snippet lang=c :
     * #define SIOCADDRT 35083
     * }
     */
    public static int SIOCADDRT() {
        return SIOCADDRT;
    }
    private static final int SIOCDELRT = (int)35084L;
    /**
     * {@snippet lang=c :
     * #define SIOCDELRT 35084
     * }
     */
    public static int SIOCDELRT() {
        return SIOCDELRT;
    }
    private static final int SIOCRTMSG = (int)35085L;
    /**
     * {@snippet lang=c :
     * #define SIOCRTMSG 35085
     * }
     */
    public static int SIOCRTMSG() {
        return SIOCRTMSG;
    }
    private static final int SIOCGIFNAME = (int)35088L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFNAME 35088
     * }
     */
    public static int SIOCGIFNAME() {
        return SIOCGIFNAME;
    }
    private static final int SIOCSIFLINK = (int)35089L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFLINK 35089
     * }
     */
    public static int SIOCSIFLINK() {
        return SIOCSIFLINK;
    }
    private static final int SIOCGIFCONF = (int)35090L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFCONF 35090
     * }
     */
    public static int SIOCGIFCONF() {
        return SIOCGIFCONF;
    }
    private static final int SIOCGIFFLAGS = (int)35091L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFFLAGS 35091
     * }
     */
    public static int SIOCGIFFLAGS() {
        return SIOCGIFFLAGS;
    }
    private static final int SIOCSIFFLAGS = (int)35092L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFFLAGS 35092
     * }
     */
    public static int SIOCSIFFLAGS() {
        return SIOCSIFFLAGS;
    }
    private static final int SIOCGIFADDR = (int)35093L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFADDR 35093
     * }
     */
    public static int SIOCGIFADDR() {
        return SIOCGIFADDR;
    }
    private static final int SIOCSIFADDR = (int)35094L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFADDR 35094
     * }
     */
    public static int SIOCSIFADDR() {
        return SIOCSIFADDR;
    }
    private static final int SIOCGIFDSTADDR = (int)35095L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFDSTADDR 35095
     * }
     */
    public static int SIOCGIFDSTADDR() {
        return SIOCGIFDSTADDR;
    }
    private static final int SIOCSIFDSTADDR = (int)35096L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFDSTADDR 35096
     * }
     */
    public static int SIOCSIFDSTADDR() {
        return SIOCSIFDSTADDR;
    }
    private static final int SIOCGIFBRDADDR = (int)35097L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFBRDADDR 35097
     * }
     */
    public static int SIOCGIFBRDADDR() {
        return SIOCGIFBRDADDR;
    }
    private static final int SIOCSIFBRDADDR = (int)35098L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFBRDADDR 35098
     * }
     */
    public static int SIOCSIFBRDADDR() {
        return SIOCSIFBRDADDR;
    }
    private static final int SIOCGIFNETMASK = (int)35099L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFNETMASK 35099
     * }
     */
    public static int SIOCGIFNETMASK() {
        return SIOCGIFNETMASK;
    }
    private static final int SIOCSIFNETMASK = (int)35100L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFNETMASK 35100
     * }
     */
    public static int SIOCSIFNETMASK() {
        return SIOCSIFNETMASK;
    }
    private static final int SIOCGIFMETRIC = (int)35101L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFMETRIC 35101
     * }
     */
    public static int SIOCGIFMETRIC() {
        return SIOCGIFMETRIC;
    }
    private static final int SIOCSIFMETRIC = (int)35102L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFMETRIC 35102
     * }
     */
    public static int SIOCSIFMETRIC() {
        return SIOCSIFMETRIC;
    }
    private static final int SIOCGIFMEM = (int)35103L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFMEM 35103
     * }
     */
    public static int SIOCGIFMEM() {
        return SIOCGIFMEM;
    }
    private static final int SIOCSIFMEM = (int)35104L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFMEM 35104
     * }
     */
    public static int SIOCSIFMEM() {
        return SIOCSIFMEM;
    }
    private static final int SIOCGIFMTU = (int)35105L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFMTU 35105
     * }
     */
    public static int SIOCGIFMTU() {
        return SIOCGIFMTU;
    }
    private static final int SIOCSIFMTU = (int)35106L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFMTU 35106
     * }
     */
    public static int SIOCSIFMTU() {
        return SIOCSIFMTU;
    }
    private static final int SIOCSIFNAME = (int)35107L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFNAME 35107
     * }
     */
    public static int SIOCSIFNAME() {
        return SIOCSIFNAME;
    }
    private static final int SIOCSIFHWADDR = (int)35108L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFHWADDR 35108
     * }
     */
    public static int SIOCSIFHWADDR() {
        return SIOCSIFHWADDR;
    }
    private static final int SIOCGIFENCAP = (int)35109L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFENCAP 35109
     * }
     */
    public static int SIOCGIFENCAP() {
        return SIOCGIFENCAP;
    }
    private static final int SIOCSIFENCAP = (int)35110L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFENCAP 35110
     * }
     */
    public static int SIOCSIFENCAP() {
        return SIOCSIFENCAP;
    }
    private static final int SIOCGIFHWADDR = (int)35111L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFHWADDR 35111
     * }
     */
    public static int SIOCGIFHWADDR() {
        return SIOCGIFHWADDR;
    }
    private static final int SIOCGIFSLAVE = (int)35113L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFSLAVE 35113
     * }
     */
    public static int SIOCGIFSLAVE() {
        return SIOCGIFSLAVE;
    }
    private static final int SIOCSIFSLAVE = (int)35120L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFSLAVE 35120
     * }
     */
    public static int SIOCSIFSLAVE() {
        return SIOCSIFSLAVE;
    }
    private static final int SIOCADDMULTI = (int)35121L;
    /**
     * {@snippet lang=c :
     * #define SIOCADDMULTI 35121
     * }
     */
    public static int SIOCADDMULTI() {
        return SIOCADDMULTI;
    }
    private static final int SIOCDELMULTI = (int)35122L;
    /**
     * {@snippet lang=c :
     * #define SIOCDELMULTI 35122
     * }
     */
    public static int SIOCDELMULTI() {
        return SIOCDELMULTI;
    }
    private static final int SIOCGIFINDEX = (int)35123L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFINDEX 35123
     * }
     */
    public static int SIOCGIFINDEX() {
        return SIOCGIFINDEX;
    }
    private static final int SIOCSIFPFLAGS = (int)35124L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFPFLAGS 35124
     * }
     */
    public static int SIOCSIFPFLAGS() {
        return SIOCSIFPFLAGS;
    }
    private static final int SIOCGIFPFLAGS = (int)35125L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFPFLAGS 35125
     * }
     */
    public static int SIOCGIFPFLAGS() {
        return SIOCGIFPFLAGS;
    }
    private static final int SIOCDIFADDR = (int)35126L;
    /**
     * {@snippet lang=c :
     * #define SIOCDIFADDR 35126
     * }
     */
    public static int SIOCDIFADDR() {
        return SIOCDIFADDR;
    }
    private static final int SIOCSIFHWBROADCAST = (int)35127L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFHWBROADCAST 35127
     * }
     */
    public static int SIOCSIFHWBROADCAST() {
        return SIOCSIFHWBROADCAST;
    }
    private static final int SIOCGIFCOUNT = (int)35128L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFCOUNT 35128
     * }
     */
    public static int SIOCGIFCOUNT() {
        return SIOCGIFCOUNT;
    }
    private static final int SIOCGIFBR = (int)35136L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFBR 35136
     * }
     */
    public static int SIOCGIFBR() {
        return SIOCGIFBR;
    }
    private static final int SIOCSIFBR = (int)35137L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFBR 35137
     * }
     */
    public static int SIOCSIFBR() {
        return SIOCSIFBR;
    }
    private static final int SIOCGIFTXQLEN = (int)35138L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFTXQLEN 35138
     * }
     */
    public static int SIOCGIFTXQLEN() {
        return SIOCGIFTXQLEN;
    }
    private static final int SIOCSIFTXQLEN = (int)35139L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFTXQLEN 35139
     * }
     */
    public static int SIOCSIFTXQLEN() {
        return SIOCSIFTXQLEN;
    }
    private static final int SIOCETHTOOL = (int)35142L;
    /**
     * {@snippet lang=c :
     * #define SIOCETHTOOL 35142
     * }
     */
    public static int SIOCETHTOOL() {
        return SIOCETHTOOL;
    }
    private static final int SIOCGMIIPHY = (int)35143L;
    /**
     * {@snippet lang=c :
     * #define SIOCGMIIPHY 35143
     * }
     */
    public static int SIOCGMIIPHY() {
        return SIOCGMIIPHY;
    }
    private static final int SIOCGMIIREG = (int)35144L;
    /**
     * {@snippet lang=c :
     * #define SIOCGMIIREG 35144
     * }
     */
    public static int SIOCGMIIREG() {
        return SIOCGMIIREG;
    }
    private static final int SIOCSMIIREG = (int)35145L;
    /**
     * {@snippet lang=c :
     * #define SIOCSMIIREG 35145
     * }
     */
    public static int SIOCSMIIREG() {
        return SIOCSMIIREG;
    }
    private static final int SIOCWANDEV = (int)35146L;
    /**
     * {@snippet lang=c :
     * #define SIOCWANDEV 35146
     * }
     */
    public static int SIOCWANDEV() {
        return SIOCWANDEV;
    }
    private static final int SIOCOUTQNSD = (int)35147L;
    /**
     * {@snippet lang=c :
     * #define SIOCOUTQNSD 35147
     * }
     */
    public static int SIOCOUTQNSD() {
        return SIOCOUTQNSD;
    }
    private static final int SIOCGSKNS = (int)35148L;
    /**
     * {@snippet lang=c :
     * #define SIOCGSKNS 35148
     * }
     */
    public static int SIOCGSKNS() {
        return SIOCGSKNS;
    }
    private static final int SIOCDARP = (int)35155L;
    /**
     * {@snippet lang=c :
     * #define SIOCDARP 35155
     * }
     */
    public static int SIOCDARP() {
        return SIOCDARP;
    }
    private static final int SIOCGARP = (int)35156L;
    /**
     * {@snippet lang=c :
     * #define SIOCGARP 35156
     * }
     */
    public static int SIOCGARP() {
        return SIOCGARP;
    }
    private static final int SIOCSARP = (int)35157L;
    /**
     * {@snippet lang=c :
     * #define SIOCSARP 35157
     * }
     */
    public static int SIOCSARP() {
        return SIOCSARP;
    }
    private static final int SIOCDRARP = (int)35168L;
    /**
     * {@snippet lang=c :
     * #define SIOCDRARP 35168
     * }
     */
    public static int SIOCDRARP() {
        return SIOCDRARP;
    }
    private static final int SIOCGRARP = (int)35169L;
    /**
     * {@snippet lang=c :
     * #define SIOCGRARP 35169
     * }
     */
    public static int SIOCGRARP() {
        return SIOCGRARP;
    }
    private static final int SIOCSRARP = (int)35170L;
    /**
     * {@snippet lang=c :
     * #define SIOCSRARP 35170
     * }
     */
    public static int SIOCSRARP() {
        return SIOCSRARP;
    }
    private static final int SIOCGIFMAP = (int)35184L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFMAP 35184
     * }
     */
    public static int SIOCGIFMAP() {
        return SIOCGIFMAP;
    }
    private static final int SIOCSIFMAP = (int)35185L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFMAP 35185
     * }
     */
    public static int SIOCSIFMAP() {
        return SIOCSIFMAP;
    }
    private static final int SIOCADDDLCI = (int)35200L;
    /**
     * {@snippet lang=c :
     * #define SIOCADDDLCI 35200
     * }
     */
    public static int SIOCADDDLCI() {
        return SIOCADDDLCI;
    }
    private static final int SIOCDELDLCI = (int)35201L;
    /**
     * {@snippet lang=c :
     * #define SIOCDELDLCI 35201
     * }
     */
    public static int SIOCDELDLCI() {
        return SIOCDELDLCI;
    }
    private static final int SIOCGIFVLAN = (int)35202L;
    /**
     * {@snippet lang=c :
     * #define SIOCGIFVLAN 35202
     * }
     */
    public static int SIOCGIFVLAN() {
        return SIOCGIFVLAN;
    }
    private static final int SIOCSIFVLAN = (int)35203L;
    /**
     * {@snippet lang=c :
     * #define SIOCSIFVLAN 35203
     * }
     */
    public static int SIOCSIFVLAN() {
        return SIOCSIFVLAN;
    }
    private static final int SIOCBONDENSLAVE = (int)35216L;
    /**
     * {@snippet lang=c :
     * #define SIOCBONDENSLAVE 35216
     * }
     */
    public static int SIOCBONDENSLAVE() {
        return SIOCBONDENSLAVE;
    }
    private static final int SIOCBONDRELEASE = (int)35217L;
    /**
     * {@snippet lang=c :
     * #define SIOCBONDRELEASE 35217
     * }
     */
    public static int SIOCBONDRELEASE() {
        return SIOCBONDRELEASE;
    }
    private static final int SIOCBONDSETHWADDR = (int)35218L;
    /**
     * {@snippet lang=c :
     * #define SIOCBONDSETHWADDR 35218
     * }
     */
    public static int SIOCBONDSETHWADDR() {
        return SIOCBONDSETHWADDR;
    }
    private static final int SIOCBONDSLAVEINFOQUERY = (int)35219L;
    /**
     * {@snippet lang=c :
     * #define SIOCBONDSLAVEINFOQUERY 35219
     * }
     */
    public static int SIOCBONDSLAVEINFOQUERY() {
        return SIOCBONDSLAVEINFOQUERY;
    }
    private static final int SIOCBONDINFOQUERY = (int)35220L;
    /**
     * {@snippet lang=c :
     * #define SIOCBONDINFOQUERY 35220
     * }
     */
    public static int SIOCBONDINFOQUERY() {
        return SIOCBONDINFOQUERY;
    }
    private static final int SIOCBONDCHANGEACTIVE = (int)35221L;
    /**
     * {@snippet lang=c :
     * #define SIOCBONDCHANGEACTIVE 35221
     * }
     */
    public static int SIOCBONDCHANGEACTIVE() {
        return SIOCBONDCHANGEACTIVE;
    }
    private static final int SIOCBRADDBR = (int)35232L;
    /**
     * {@snippet lang=c :
     * #define SIOCBRADDBR 35232
     * }
     */
    public static int SIOCBRADDBR() {
        return SIOCBRADDBR;
    }
    private static final int SIOCBRDELBR = (int)35233L;
    /**
     * {@snippet lang=c :
     * #define SIOCBRDELBR 35233
     * }
     */
    public static int SIOCBRDELBR() {
        return SIOCBRDELBR;
    }
    private static final int SIOCBRADDIF = (int)35234L;
    /**
     * {@snippet lang=c :
     * #define SIOCBRADDIF 35234
     * }
     */
    public static int SIOCBRADDIF() {
        return SIOCBRADDIF;
    }
    private static final int SIOCBRDELIF = (int)35235L;
    /**
     * {@snippet lang=c :
     * #define SIOCBRDELIF 35235
     * }
     */
    public static int SIOCBRDELIF() {
        return SIOCBRDELIF;
    }
    private static final int SIOCSHWTSTAMP = (int)35248L;
    /**
     * {@snippet lang=c :
     * #define SIOCSHWTSTAMP 35248
     * }
     */
    public static int SIOCSHWTSTAMP() {
        return SIOCSHWTSTAMP;
    }
    private static final int SIOCGHWTSTAMP = (int)35249L;
    /**
     * {@snippet lang=c :
     * #define SIOCGHWTSTAMP 35249
     * }
     */
    public static int SIOCGHWTSTAMP() {
        return SIOCGHWTSTAMP;
    }
    private static final int SIOCDEVPRIVATE = (int)35312L;
    /**
     * {@snippet lang=c :
     * #define SIOCDEVPRIVATE 35312
     * }
     */
    public static int SIOCDEVPRIVATE() {
        return SIOCDEVPRIVATE;
    }
    private static final int SIOCPROTOPRIVATE = (int)35296L;
    /**
     * {@snippet lang=c :
     * #define SIOCPROTOPRIVATE 35296
     * }
     */
    public static int SIOCPROTOPRIVATE() {
        return SIOCPROTOPRIVATE;
    }
    private static final int TIPC_NODE_STATE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODE_STATE 0
     * }
     */
    public static int TIPC_NODE_STATE() {
        return TIPC_NODE_STATE;
    }
    private static final int TIPC_TOP_SRV = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_TOP_SRV 1
     * }
     */
    public static int TIPC_TOP_SRV() {
        return TIPC_TOP_SRV;
    }
    private static final int TIPC_LINK_STATE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_LINK_STATE 2
     * }
     */
    public static int TIPC_LINK_STATE() {
        return TIPC_LINK_STATE;
    }
    private static final int TIPC_RESERVED_TYPES = (int)64L;
    /**
     * {@snippet lang=c :
     * #define TIPC_RESERVED_TYPES 64
     * }
     */
    public static int TIPC_RESERVED_TYPES() {
        return TIPC_RESERVED_TYPES;
    }
    private static final int TIPC_LOW_IMPORTANCE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define TIPC_LOW_IMPORTANCE 0
     * }
     */
    public static int TIPC_LOW_IMPORTANCE() {
        return TIPC_LOW_IMPORTANCE;
    }
    private static final int TIPC_MEDIUM_IMPORTANCE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MEDIUM_IMPORTANCE 1
     * }
     */
    public static int TIPC_MEDIUM_IMPORTANCE() {
        return TIPC_MEDIUM_IMPORTANCE;
    }
    private static final int TIPC_HIGH_IMPORTANCE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_HIGH_IMPORTANCE 2
     * }
     */
    public static int TIPC_HIGH_IMPORTANCE() {
        return TIPC_HIGH_IMPORTANCE;
    }
    private static final int TIPC_CRITICAL_IMPORTANCE = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CRITICAL_IMPORTANCE 3
     * }
     */
    public static int TIPC_CRITICAL_IMPORTANCE() {
        return TIPC_CRITICAL_IMPORTANCE;
    }
    private static final int TIPC_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define TIPC_OK 0
     * }
     */
    public static int TIPC_OK() {
        return TIPC_OK;
    }
    private static final int TIPC_ERR_NO_NAME = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ERR_NO_NAME 1
     * }
     */
    public static int TIPC_ERR_NO_NAME() {
        return TIPC_ERR_NO_NAME;
    }
    private static final int TIPC_ERR_NO_PORT = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ERR_NO_PORT 2
     * }
     */
    public static int TIPC_ERR_NO_PORT() {
        return TIPC_ERR_NO_PORT;
    }
    private static final int TIPC_ERR_NO_NODE = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ERR_NO_NODE 3
     * }
     */
    public static int TIPC_ERR_NO_NODE() {
        return TIPC_ERR_NO_NODE;
    }
    private static final int TIPC_ERR_OVERLOAD = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ERR_OVERLOAD 4
     * }
     */
    public static int TIPC_ERR_OVERLOAD() {
        return TIPC_ERR_OVERLOAD;
    }
    private static final int TIPC_CONN_SHUTDOWN = (int)5L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CONN_SHUTDOWN 5
     * }
     */
    public static int TIPC_CONN_SHUTDOWN() {
        return TIPC_CONN_SHUTDOWN;
    }
    private static final int TIPC_SUB_PORTS = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SUB_PORTS 1
     * }
     */
    public static int TIPC_SUB_PORTS() {
        return TIPC_SUB_PORTS;
    }
    private static final int TIPC_SUB_SERVICE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SUB_SERVICE 2
     * }
     */
    public static int TIPC_SUB_SERVICE() {
        return TIPC_SUB_SERVICE;
    }
    private static final int TIPC_SUB_CANCEL = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SUB_CANCEL 4
     * }
     */
    public static int TIPC_SUB_CANCEL() {
        return TIPC_SUB_CANCEL;
    }
    private static final int TIPC_PUBLISHED = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_PUBLISHED 1
     * }
     */
    public static int TIPC_PUBLISHED() {
        return TIPC_PUBLISHED;
    }
    private static final int TIPC_WITHDRAWN = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_WITHDRAWN 2
     * }
     */
    public static int TIPC_WITHDRAWN() {
        return TIPC_WITHDRAWN;
    }
    private static final int TIPC_SUBSCR_TIMEOUT = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SUBSCR_TIMEOUT 3
     * }
     */
    public static int TIPC_SUBSCR_TIMEOUT() {
        return TIPC_SUBSCR_TIMEOUT;
    }
    private static final int AF_TIPC = (int)30L;
    /**
     * {@snippet lang=c :
     * #define AF_TIPC 30
     * }
     */
    public static int AF_TIPC() {
        return AF_TIPC;
    }
    private static final int SOL_TIPC = (int)271L;
    /**
     * {@snippet lang=c :
     * #define SOL_TIPC 271
     * }
     */
    public static int SOL_TIPC() {
        return SOL_TIPC;
    }
    private static final int TIPC_ADDR_MCAST = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ADDR_MCAST 1
     * }
     */
    public static int TIPC_ADDR_MCAST() {
        return TIPC_ADDR_MCAST;
    }
    private static final int TIPC_SERVICE_RANGE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SERVICE_RANGE 1
     * }
     */
    public static int TIPC_SERVICE_RANGE() {
        return TIPC_SERVICE_RANGE;
    }
    private static final int TIPC_SERVICE_ADDR = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SERVICE_ADDR 2
     * }
     */
    public static int TIPC_SERVICE_ADDR() {
        return TIPC_SERVICE_ADDR;
    }
    private static final int TIPC_SOCKET_ADDR = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SOCKET_ADDR 3
     * }
     */
    public static int TIPC_SOCKET_ADDR() {
        return TIPC_SOCKET_ADDR;
    }
    private static final int TIPC_ERRINFO = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ERRINFO 1
     * }
     */
    public static int TIPC_ERRINFO() {
        return TIPC_ERRINFO;
    }
    private static final int TIPC_RETDATA = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_RETDATA 2
     * }
     */
    public static int TIPC_RETDATA() {
        return TIPC_RETDATA;
    }
    private static final int TIPC_DESTNAME = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TIPC_DESTNAME 3
     * }
     */
    public static int TIPC_DESTNAME() {
        return TIPC_DESTNAME;
    }
    private static final int TIPC_IMPORTANCE = (int)127L;
    /**
     * {@snippet lang=c :
     * #define TIPC_IMPORTANCE 127
     * }
     */
    public static int TIPC_IMPORTANCE() {
        return TIPC_IMPORTANCE;
    }
    private static final int TIPC_SRC_DROPPABLE = (int)128L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SRC_DROPPABLE 128
     * }
     */
    public static int TIPC_SRC_DROPPABLE() {
        return TIPC_SRC_DROPPABLE;
    }
    private static final int TIPC_DEST_DROPPABLE = (int)129L;
    /**
     * {@snippet lang=c :
     * #define TIPC_DEST_DROPPABLE 129
     * }
     */
    public static int TIPC_DEST_DROPPABLE() {
        return TIPC_DEST_DROPPABLE;
    }
    private static final int TIPC_CONN_TIMEOUT = (int)130L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CONN_TIMEOUT 130
     * }
     */
    public static int TIPC_CONN_TIMEOUT() {
        return TIPC_CONN_TIMEOUT;
    }
    private static final int TIPC_NODE_RECVQ_DEPTH = (int)131L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODE_RECVQ_DEPTH 131
     * }
     */
    public static int TIPC_NODE_RECVQ_DEPTH() {
        return TIPC_NODE_RECVQ_DEPTH;
    }
    private static final int TIPC_SOCK_RECVQ_DEPTH = (int)132L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SOCK_RECVQ_DEPTH 132
     * }
     */
    public static int TIPC_SOCK_RECVQ_DEPTH() {
        return TIPC_SOCK_RECVQ_DEPTH;
    }
    private static final int TIPC_MCAST_BROADCAST = (int)133L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MCAST_BROADCAST 133
     * }
     */
    public static int TIPC_MCAST_BROADCAST() {
        return TIPC_MCAST_BROADCAST;
    }
    private static final int TIPC_MCAST_REPLICAST = (int)134L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MCAST_REPLICAST 134
     * }
     */
    public static int TIPC_MCAST_REPLICAST() {
        return TIPC_MCAST_REPLICAST;
    }
    private static final int TIPC_GROUP_JOIN = (int)135L;
    /**
     * {@snippet lang=c :
     * #define TIPC_GROUP_JOIN 135
     * }
     */
    public static int TIPC_GROUP_JOIN() {
        return TIPC_GROUP_JOIN;
    }
    private static final int TIPC_GROUP_LEAVE = (int)136L;
    /**
     * {@snippet lang=c :
     * #define TIPC_GROUP_LEAVE 136
     * }
     */
    public static int TIPC_GROUP_LEAVE() {
        return TIPC_GROUP_LEAVE;
    }
    private static final int TIPC_SOCK_RECVQ_USED = (int)137L;
    /**
     * {@snippet lang=c :
     * #define TIPC_SOCK_RECVQ_USED 137
     * }
     */
    public static int TIPC_SOCK_RECVQ_USED() {
        return TIPC_SOCK_RECVQ_USED;
    }
    private static final int TIPC_NODELAY = (int)138L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODELAY 138
     * }
     */
    public static int TIPC_NODELAY() {
        return TIPC_NODELAY;
    }
    private static final int TIPC_GROUP_LOOPBACK = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_GROUP_LOOPBACK 1
     * }
     */
    public static int TIPC_GROUP_LOOPBACK() {
        return TIPC_GROUP_LOOPBACK;
    }
    private static final int TIPC_GROUP_MEMBER_EVTS = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_GROUP_MEMBER_EVTS 2
     * }
     */
    public static int TIPC_GROUP_MEMBER_EVTS() {
        return TIPC_GROUP_MEMBER_EVTS;
    }
    private static final int TIPC_NODEID_LEN = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODEID_LEN 16
     * }
     */
    public static int TIPC_NODEID_LEN() {
        return TIPC_NODEID_LEN;
    }
    private static final int TIPC_MAX_MEDIA_NAME = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MAX_MEDIA_NAME 16
     * }
     */
    public static int TIPC_MAX_MEDIA_NAME() {
        return TIPC_MAX_MEDIA_NAME;
    }
    private static final int TIPC_MAX_IF_NAME = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MAX_IF_NAME 16
     * }
     */
    public static int TIPC_MAX_IF_NAME() {
        return TIPC_MAX_IF_NAME;
    }
    private static final int TIPC_MAX_BEARER_NAME = (int)32L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MAX_BEARER_NAME 32
     * }
     */
    public static int TIPC_MAX_BEARER_NAME() {
        return TIPC_MAX_BEARER_NAME;
    }
    private static final int TIPC_MAX_LINK_NAME = (int)68L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MAX_LINK_NAME 68
     * }
     */
    public static int TIPC_MAX_LINK_NAME() {
        return TIPC_MAX_LINK_NAME;
    }
    private static final int TIPC_CFG_SRV = (int)0L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CFG_SRV 0
     * }
     */
    public static int TIPC_CFG_SRV() {
        return TIPC_CFG_SRV;
    }
    private static final int TIPC_ZONE_SCOPE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ZONE_SCOPE 1
     * }
     */
    public static int TIPC_ZONE_SCOPE() {
        return TIPC_ZONE_SCOPE;
    }
    private static final int TIPC_ADDR_NAMESEQ = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ADDR_NAMESEQ 1
     * }
     */
    public static int TIPC_ADDR_NAMESEQ() {
        return TIPC_ADDR_NAMESEQ;
    }
    private static final int TIPC_ADDR_NAME = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ADDR_NAME 2
     * }
     */
    public static int TIPC_ADDR_NAME() {
        return TIPC_ADDR_NAME;
    }
    private static final int TIPC_ADDR_ID = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ADDR_ID 3
     * }
     */
    public static int TIPC_ADDR_ID() {
        return TIPC_ADDR_ID;
    }
    private static final int TIPC_NODE_BITS = (int)12L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODE_BITS 12
     * }
     */
    public static int TIPC_NODE_BITS() {
        return TIPC_NODE_BITS;
    }
    private static final int TIPC_CLUSTER_BITS = (int)12L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CLUSTER_BITS 12
     * }
     */
    public static int TIPC_CLUSTER_BITS() {
        return TIPC_CLUSTER_BITS;
    }
    private static final int TIPC_ZONE_BITS = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ZONE_BITS 8
     * }
     */
    public static int TIPC_ZONE_BITS() {
        return TIPC_ZONE_BITS;
    }
    private static final int TIPC_NODE_OFFSET = (int)0L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODE_OFFSET 0
     * }
     */
    public static int TIPC_NODE_OFFSET() {
        return TIPC_NODE_OFFSET;
    }
    /**
     * {@snippet lang=c :
     * typedef signed char __s8
     * }
     */
    public static final OfByte __s8 = tipc_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned char __u8
     * }
     */
    public static final OfByte __u8 = tipc_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef short __s16
     * }
     */
    public static final OfShort __s16 = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __u16
     * }
     */
    public static final OfShort __u16 = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int __s32
     * }
     */
    public static final OfInt __s32 = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __u32
     * }
     */
    public static final OfInt __u32 = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long long __s64
     * }
     */
    public static final OfLong __s64 = tipc_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long long __u64
     * }
     */
    public static final OfLong __u64 = tipc_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef int __kernel_key_t
     * }
     */
    public static final OfInt __kernel_key_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __kernel_mqd_t
     * }
     */
    public static final OfInt __kernel_mqd_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __kernel_old_uid_t
     * }
     */
    public static final OfShort __kernel_old_uid_t = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __kernel_old_gid_t
     * }
     */
    public static final OfShort __kernel_old_gid_t = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __kernel_old_dev_t
     * }
     */
    public static final OfLong __kernel_old_dev_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long __kernel_long_t
     * }
     */
    public static final OfLong __kernel_long_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long __kernel_ulong_t
     * }
     */
    public static final OfLong __kernel_ulong_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __kernel_ulong_t __kernel_ino_t
     * }
     */
    public static final OfLong __kernel_ino_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __kernel_mode_t
     * }
     */
    public static final OfInt __kernel_mode_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __kernel_pid_t
     * }
     */
    public static final OfInt __kernel_pid_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __kernel_ipc_pid_t
     * }
     */
    public static final OfInt __kernel_ipc_pid_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __kernel_uid_t
     * }
     */
    public static final OfInt __kernel_uid_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __kernel_gid_t
     * }
     */
    public static final OfInt __kernel_gid_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __kernel_long_t __kernel_suseconds_t
     * }
     */
    public static final OfLong __kernel_suseconds_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef int __kernel_daddr_t
     * }
     */
    public static final OfInt __kernel_daddr_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __kernel_uid32_t
     * }
     */
    public static final OfInt __kernel_uid32_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __kernel_gid32_t
     * }
     */
    public static final OfInt __kernel_gid32_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __kernel_ulong_t __kernel_size_t
     * }
     */
    public static final OfLong __kernel_size_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __kernel_long_t __kernel_ssize_t
     * }
     */
    public static final OfLong __kernel_ssize_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __kernel_long_t __kernel_ptrdiff_t
     * }
     */
    public static final OfLong __kernel_ptrdiff_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __kernel_long_t __kernel_off_t
     * }
     */
    public static final OfLong __kernel_off_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long long __kernel_loff_t
     * }
     */
    public static final OfLong __kernel_loff_t = tipc_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __kernel_long_t __kernel_old_time_t
     * }
     */
    public static final OfLong __kernel_old_time_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef __kernel_long_t __kernel_time_t
     * }
     */
    public static final OfLong __kernel_time_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef long long __kernel_time64_t
     * }
     */
    public static final OfLong __kernel_time64_t = tipc_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __kernel_long_t __kernel_clock_t
     * }
     */
    public static final OfLong __kernel_clock_t = tipc_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef int __kernel_timer_t
     * }
     */
    public static final OfInt __kernel_timer_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef int __kernel_clockid_t
     * }
     */
    public static final OfInt __kernel_clockid_t = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef char *__kernel_caddr_t
     * }
     */
    public static final AddressLayout __kernel_caddr_t = tipc_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __kernel_uid16_t
     * }
     */
    public static final OfShort __kernel_uid16_t = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short __kernel_gid16_t
     * }
     */
    public static final OfShort __kernel_gid16_t = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __u16 __le16
     * }
     */
    public static final OfShort __le16 = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __u16 __be16
     * }
     */
    public static final OfShort __be16 = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __u32 __le32
     * }
     */
    public static final OfInt __le32 = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __u32 __be32
     * }
     */
    public static final OfInt __be32 = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef __u64 __le64
     * }
     */
    public static final OfLong __le64 = tipc_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __u64 __be64
     * }
     */
    public static final OfLong __be64 = tipc_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef __u16 __sum16
     * }
     */
    public static final OfShort __sum16 = tipc_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef __u32 __wsum
     * }
     */
    public static final OfInt __wsum = tipc_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int __poll_t
     * }
     */
    public static final OfInt __poll_t = tipc_h.C_INT;
    private static final int TIPC_CLUSTER_SCOPE = (int)2L;
    /**
     * {@snippet lang=c :
     * enum tipc_scope.TIPC_CLUSTER_SCOPE = 2
     * }
     */
    public static int TIPC_CLUSTER_SCOPE() {
        return TIPC_CLUSTER_SCOPE;
    }
    private static final int TIPC_NODE_SCOPE = (int)3L;
    /**
     * {@snippet lang=c :
     * enum tipc_scope.TIPC_NODE_SCOPE = 3
     * }
     */
    public static int TIPC_NODE_SCOPE() {
        return TIPC_NODE_SCOPE;
    }
    private static final int SIOCGSTAMP = (int)35078L;
    /**
     * {@snippet lang=c :
     * #define SIOCGSTAMP 35078
     * }
     */
    public static int SIOCGSTAMP() {
        return SIOCGSTAMP;
    }
    private static final int SIOCGSTAMPNS = (int)35079L;
    /**
     * {@snippet lang=c :
     * #define SIOCGSTAMPNS 35079
     * }
     */
    public static int SIOCGSTAMPNS() {
        return SIOCGSTAMPNS;
    }
    private static final int SIOGIFINDEX = (int)35123L;
    /**
     * {@snippet lang=c :
     * #define SIOGIFINDEX 35123
     * }
     */
    public static int SIOGIFINDEX() {
        return SIOGIFINDEX;
    }
    private static final int TIPC_MAX_USER_MSG_SIZE = (int)66000L;
    /**
     * {@snippet lang=c :
     * #define TIPC_MAX_USER_MSG_SIZE 66000
     * }
     */
    public static int TIPC_MAX_USER_MSG_SIZE() {
        return TIPC_MAX_USER_MSG_SIZE;
    }
    private static final int TIPC_WAIT_FOREVER = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define TIPC_WAIT_FOREVER -1
     * }
     */
    public static int TIPC_WAIT_FOREVER() {
        return TIPC_WAIT_FOREVER;
    }
    private static final int PF_TIPC = (int)30L;
    /**
     * {@snippet lang=c :
     * #define PF_TIPC 30
     * }
     */
    public static int PF_TIPC() {
        return PF_TIPC;
    }
    private static final int SIOCGETLINKNAME = (int)35296L;
    /**
     * {@snippet lang=c :
     * #define SIOCGETLINKNAME 35296
     * }
     */
    public static int SIOCGETLINKNAME() {
        return SIOCGETLINKNAME;
    }
    private static final int SIOCGETNODEID = (int)35297L;
    /**
     * {@snippet lang=c :
     * #define SIOCGETNODEID 35297
     * }
     */
    public static int SIOCGETNODEID() {
        return SIOCGETNODEID;
    }
    private static final int TIPC_AEAD_ALG_NAME = (int)32L;
    /**
     * {@snippet lang=c :
     * #define TIPC_AEAD_ALG_NAME 32
     * }
     */
    public static int TIPC_AEAD_ALG_NAME() {
        return TIPC_AEAD_ALG_NAME;
    }
    private static final int TIPC_AEAD_KEYLEN_MIN = (int)20L;
    /**
     * {@snippet lang=c :
     * #define TIPC_AEAD_KEYLEN_MIN 20
     * }
     */
    public static int TIPC_AEAD_KEYLEN_MIN() {
        return TIPC_AEAD_KEYLEN_MIN;
    }
    private static final int TIPC_AEAD_KEYLEN_MAX = (int)36L;
    /**
     * {@snippet lang=c :
     * #define TIPC_AEAD_KEYLEN_MAX 36
     * }
     */
    public static int TIPC_AEAD_KEYLEN_MAX() {
        return TIPC_AEAD_KEYLEN_MAX;
    }
    private static final long TIPC_AEAD_KEY_SIZE_MAX = 72L;
    /**
     * {@snippet lang=c :
     * #define TIPC_AEAD_KEY_SIZE_MAX 72
     * }
     */
    public static long TIPC_AEAD_KEY_SIZE_MAX() {
        return TIPC_AEAD_KEY_SIZE_MAX;
    }
    private static final int TIPC_REKEYING_NOW = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define TIPC_REKEYING_NOW 4294967295
     * }
     */
    public static int TIPC_REKEYING_NOW() {
        return TIPC_REKEYING_NOW;
    }
    private static final int TIPC_CLUSTER_OFFSET = (int)12L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CLUSTER_OFFSET 12
     * }
     */
    public static int TIPC_CLUSTER_OFFSET() {
        return TIPC_CLUSTER_OFFSET;
    }
    private static final int TIPC_ZONE_OFFSET = (int)24L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ZONE_OFFSET 24
     * }
     */
    public static int TIPC_ZONE_OFFSET() {
        return TIPC_ZONE_OFFSET;
    }
    private static final long TIPC_NODE_SIZE = 4095L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODE_SIZE 4095
     * }
     */
    public static long TIPC_NODE_SIZE() {
        return TIPC_NODE_SIZE;
    }
    private static final long TIPC_CLUSTER_SIZE = 4095L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CLUSTER_SIZE 4095
     * }
     */
    public static long TIPC_CLUSTER_SIZE() {
        return TIPC_CLUSTER_SIZE;
    }
    private static final long TIPC_ZONE_SIZE = 255L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ZONE_SIZE 255
     * }
     */
    public static long TIPC_ZONE_SIZE() {
        return TIPC_ZONE_SIZE;
    }
    private static final long TIPC_NODE_MASK = 4095L;
    /**
     * {@snippet lang=c :
     * #define TIPC_NODE_MASK 4095
     * }
     */
    public static long TIPC_NODE_MASK() {
        return TIPC_NODE_MASK;
    }
    private static final long TIPC_CLUSTER_MASK = 16773120L;
    /**
     * {@snippet lang=c :
     * #define TIPC_CLUSTER_MASK 16773120
     * }
     */
    public static long TIPC_CLUSTER_MASK() {
        return TIPC_CLUSTER_MASK;
    }
    private static final long TIPC_ZONE_MASK = 4278190080L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ZONE_MASK 4278190080
     * }
     */
    public static long TIPC_ZONE_MASK() {
        return TIPC_ZONE_MASK;
    }
    private static final long TIPC_ZONE_CLUSTER_MASK = 4294963200L;
    /**
     * {@snippet lang=c :
     * #define TIPC_ZONE_CLUSTER_MASK 4294963200
     * }
     */
    public static long TIPC_ZONE_CLUSTER_MASK() {
        return TIPC_ZONE_CLUSTER_MASK;
    }
}

